service: secure-pdf-book-2020

provider:
    name: aws
    runtime: go1.x
    profile: serverless-user
    region: ap-northeast-1
    iamRoleStatements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - !GetAtt PDFBookBucket.Arn
            - !Join 
                - ""
                - - !GetAtt PDFBookBucket.Arn
                  - "/*"
    environment:
        BUCKET_NAME: !Ref PDFBookBucket
        HOME: /tmp 

package:
    exclude:
        - ./**
    include:
        - ./bin/**

functions:
    copyobject:
        handler: bin/copyobject/main
    encrypt:
        handler: bin/encrypt/main
        layers:
            - arn:aws:lambda:ap-northeast-1:834655946912:layer:qpdf-layer:2
        environment:
            LD_LIBRARY_PATH: "/opt/qpdf/lib:$LD_LIBRARY_PATH"
            PATH: "/opt/qpdf/bin:$PATH"
    property:
        handler: bin/property/main
    sign:
        handler: bin/sign/main
    watermark:
        handler: bin/watermark/main

resources:
    Resources:
        PDFBookBucket:
            Type: AWS::S3::Bucket
            Properties:
                LifecycleConfiguration:
                    Rules:
                    - Prefix: "tmp"
                      ExpirationInDays: 1
                      Status: Enabled
                    - Prefix: "public"
                      ExpirationInDays: 7
                      Status: Enabled
    Outputs:
        PDFBookBucketName:
            Description: PDFBookBucketName
            Value: !Ref PDFBookBucket
            Export: 
                Name: ${self:service}-PDFBookBucketName
        PDFBookBucketArn:
            Description: PDFBookBucketArn
            Value: !GetAtt PDFBookBucket.Arn
            Export: 
                Name: ${self:service}-PDFBookBucketArn